### ISSUE TITLE
чтото сломалось после долгой работы :)

### ISSUE THREAD

**Issue by TOWUK** [aeonixlegit/vk-autocomment#7]
вот логи:
```

 ▌ ▐·▄ •▄      ▄▄▄· ▄• ▄▌▄▄▄▄▄       ▄▄·       • ▌ ▄ ·. • ▌ ▄ ·. ▄▄▄ . ▐ ▄ ▄▄▄▄▄
▪█·█▌█▌▄▌▪    ▐█ ▀█ █▪██▌•██  ▪     ▐█ ▌▪▪     ·██ ▐███▪·██ ▐███▪▀▄.▀·•█▌▐█•██  
▐█▐█•▐▀▀▄·    ▄█▀▀█ █▌▐█▌ ▐█.▪ ▄█▀▄ ██ ▄▄ ▄█▀▄ ▐█ ▌▐▌▐█·▐█ ▌▐▌▐█·▐▀▀▪▄▐█▐▐▌ ▐█.▪
 ███ ▐█.█▌    ▐█ ▪▐▌▐█▄█▌ ▐█▌·▐█▌.▐▌▐███▌▐█▌.▐▌██ ██▌▐█▌██ ██▌▐█▌▐█▄▄▌██▐█▌ ▐█▌·
. ▀  ·▀  ▀     ▀  ▀  ▀▀▀  ▀▀▀  ▀█▄▀▪·▀▀▀  ▀█▄▀▪▀▀  █▪▀▀▀▀▀  █▪▀▀▀ ▀▀▀ ▀▀ █▪ ▀▀▀ 

! VK AutoComment был запущен.
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are 
not handled will terminate the Node.js process with a non-zero exit code.
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:8492) UnhandledPromiseRejectionWarning: APIError: Code №29 - Rate limit reached
    at API.callMethod (C:\Users\TOWUK\Desktop\vk-autocomment\node_modules\vk-io\lib\index.js:828:39)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:8492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process 
on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
^C
```

**Comment by raywave** [comment]
Похоже, что ВКонтакте установили лимит в ~4500 запросов с одного аккаунта в день (или в час, не знаю).

Ничего не поделать, кроме как подождать час или день.
