### ISSUE TITLE
vk.setOptions is not a function

### ISSUE THREAD

**Issue by 01zhas** [aeonixlegit/vk-autocomment#8]
Что тут не так? 
TypeError: vk.setOptions is not a function
    at init (C:\Users\m1901917\Desktop\vk-autocomment-2.2.0\src\index.js:95:6)
    at Object.<anonymous> (C:\Users\m1901917\Desktop\vk-autocomment-2.2.0\src\index.js:295:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Bot was forced to exit . . .

**Comment by raywave** [comment]
Ошибка в версии vk-io (в модуле используется 4.0.0-rc.29), в версиях выше, чем в модуле - данной опции нет
